
FROM node:8.0.0
MAINTAINER Joe

RUN mkdir -p /runDIR/web
WORKDIR /runDIR/web

#ADD ./release/web /runDIR/web
COPY --from=nextjscompile /release/web /runDIR/web 
RUN cd /runDIR/web && npm install && npm run build



ENV HOST 0.0.0.0
ENV PORT 3000

EXPOSE 3000
ENTRYPOINT ["npm","start"]
