
FROM windwithlife/maven-fast:1.0

ADD pom.xml /tmp/build/
RUN cd /tmp/build && mvn -q dependency:resolve

ADD src /tmp/build/src
RUN mkdir -p /release/    
RUN cd /tmp/build && mvn -q -DskipTests=true  package && mv target/*.jar /release/app.jar
ENTRYPOINT ["tail","-f","/etc/passwd"]
