
FROM node:8.0.0 as nextjscompile
MAINTAINER Joe

RUN mkdir -p /release/web
WORKDIR /release/web

COPY ./  /release/web/

FROM node:8.10.0-slim
MAINTAINER Joe

RUN mkdir -p /runDIR/web
WORKDIR /runDIR/web

COPY --from=nextjscompile /release/web /runDIR/web 
RUN cd /runDIR/web && npm install && npm run build

ENV HOST 0.0.0.0
ENV PORT 3000

EXPOSE 3000
ENTRYPOINT ["npm","start"]
